Verstov_pro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


from home.views import home
from experiments.views import test, test_js_request
from private_notes.views import create_private_note, find_and_check_private_note, input_second_password
from audio_test.views import add_new_audio, ShowAudioTest


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home, name='home'),
    path('', include('url_shortener.urls')),
    # private notes urls
    path('private_notes/', create_private_note, name='private_notes'),
    path('private_notes/second_password/', input_second_password, name='second_password'),
    path('<str:short_id>/<slug:password>', find_and_check_private_note),
    # audio test urls
    # path('audio_test/', show_audio_test, name='show_audio_test'),
    path('audio_test/', ShowAudioTest.as_view(), name='show_audio_test'),
    path('audio_test/add/', add_new_audio, name='add_audio'),

    # my tests and experiments
    path('test/', test, name='test'),
    path('test/request/', test_js_request, name='test_js_request'),
]

# make media files available
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

url_shortener/urls.py
from django.urls import path
from .views import *

urlpatterns = (
    path('shortener/', shortener, name='shortener'),
    path('<slug:short_id>', redirect_to_main_url),

)

url_shortener/models.py
from django.db import models


class ShortenerFields(models.Model):
    """ Describes fields """
    full_url = models.URLField(max_length=1000)
    short_id = models.CharField(max_length=6, primary_key=True)
    created_at = models.DateField(auto_now_add=True)
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.full_url

url_shortener/forms.py
from django import forms
from .models import ShortenerFields
from django.core.exceptions import ValidationError
import re


class ShortenerForm(forms.ModelForm):
    class Meta:
        model = ShortenerFields
        fields = '__all__'

url_shortener/views.py
from django.contrib import messages
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.db.models import ObjectDoesNotExist
from .models import ShortenerFields
from .forms import ShortenerForm
from services.crypto import get_short_id


def shortener(request):
    if request.method == 'GET':
        return render_shortener_main_page(request)
    elif request.method == 'POST':
        # get user input (url)
        full_url = request.POST.get('full_url')
        try:
            # duplication check
            # return short_id from DB if duplicate exists
            obj = ShortenerFields.objects.get(full_url=full_url)
            # return short_id from DB without generation
            context = {'short_id': obj.pk}

        except ObjectDoesNotExist:
            # TODO переделать, чтобы главное действие происходило, не через искление
            # ToDO верификация URL на уровне сервера

            short_id = get_short_id(Fields=ShortenerFields)
            obj = ShortenerFields()
            obj.full_url = full_url
            obj.short_id = short_id
            obj.save()
            context = {'short_id': short_id}

        messages.success(request, 'Ваша ссылка создана! ')
        return render(request, 'url_shortener/get_short_url.html', context)


def redirect_to_main_url(request, short_id):
    """ redirect to target URL if short_id exists"""
    try:
        redirect_obj = ShortenerFields.objects.get(pk=short_id)
        redirect_obj.count += 1
        redirect_obj.save()
        return HttpResponseRedirect(redirect_obj.full_url)
    except ObjectDoesNotExist:
        # redirect to app's main page with error message
        messages.error(request, 'Ссылка не найдена!')
        return render_shortener_main_page(request)


def render_shortener_main_page(request):
    form = ShortenerForm()
    context = {'form': form}
    return render(request, 'url_shortener/shortener.html', context)

templates/url_shortener/get_short_url.html
{% extends 'base.html' %}

{% block sub_title %}
    Сокращатель
{% endblock %}

{% block content %}

        <h2>{{ SITE_URL }}{{ short_id }}

        </h2>
        <button onclick="copyText()" id='copy-btn' class="btn btn-outline-primary">Копировать</button>
        <button onclick="window.location.href = '{% url 'shortener' %}';" class="btn btn-outline-primary">Сократить ещё
            одну ссылку
        </button>

    <script>
        function copyText() {
            /* Copy text into clipboard */
            navigator.clipboard.writeText
            ("{{ SITE_URL }}{{ short_id }}");
            document.getElementById("copy-btn")
                .innerHTML = 'Скопировано!';
        }
    </script>

{% endblock %}

templates/url_shortener/shortener.html
{% extends 'base.html' %}

{% block sub_title %}
    Сокращатель
{% endblock %}

{% block content %}

    <form action="{% url 'shortener' %}" method="post">
        {% csrf_token %}
        <div class="col-12">
            <label for="inputAddress" class="form-label">URL</label>
            <input type="url" name="full_url" class="form-control" required id="id_full_url"
                   placeholder="Вставьте URL сюда">
        </div>
        <div class="d-grid gap-2">

            <button type="submit" class="btn btn-primary mt-3">Сократить URL</button>
</div>

    </form>

{% endblock %}